// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // Reuse iOS configuration for macOS
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEW7w-j0ase96af4d2gxH6cNsGCAQStQ0',
    appId: '1:475367390723:web:2ec12909fb0958fb7d5836',
    messagingSenderId: '475367390723',
    projectId: 'personal-wardrobe-mgr-hza',
    authDomain: 'personal-wardrobe-mgr-hza.firebaseapp.com',
    storageBucket: 'personal-wardrobe-mgr-hza.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXxeu6qzzkj2OOV12B9GSZYrKGwXpbT4A',
    appId: '1:475367390723:android:0a4d44c1417e04ad7d5836',
    messagingSenderId: '475367390723',
    projectId: 'personal-wardrobe-mgr-hza',
    storageBucket: 'personal-wardrobe-mgr-hza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvP2EfDwVJuZ710ZSvPWculTY5liYXRH0',
    appId: '1:475367390723:ios:b68b76aa26c638657d5836',
    messagingSenderId: '475367390723',
    projectId: 'personal-wardrobe-mgr-hza',
    storageBucket: 'personal-wardrobe-mgr-hza.firebasestorage.app',
    iosBundleId: 'com.example.wardrobeApp',
  );
}
